[
    {
        "scheduleDate": "2002-12-01",
        "scheduleSeason": "2002",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "38",
        "scoreAway": "21",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "MIA",
        "spreadFavorite": "-2",
        "overUnder": "37",
        "stadium": "Ralph Wilson Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "17",
        "weatherHumidity": "73",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2002-12-01",
        "scheduleSeason": "2002",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cleveland Browns",
        "scoreHome": "6",
        "scoreAway": "13",
        "teamAway": "Carolina Panthers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "CLE",
        "spreadFavorite": "-7.5",
        "overUnder": "34.5",
        "stadium": "FirstEnergy Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "26",
        "weatherWindMph": "19",
        "weatherHumidity": "61",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2002-12-01",
        "scheduleSeason": "2002",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "49",
        "scoreAway": "0",
        "teamAway": "Arizona Cardinals",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "KC",
        "spreadFavorite": "-9",
        "overUnder": "47",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "14",
        "weatherHumidity": "46",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2002-12-08",
        "scheduleSeason": "2002",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Baltimore Ravens",
        "scoreHome": "25",
        "scoreAway": "37",
        "teamAway": "New Orleans Saints",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "NO",
        "spreadFavorite": "-2",
        "overUnder": "42.5",
        "stadium": "M&T Bank Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "6",
        "weatherHumidity": "75",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2002-12-22",
        "scheduleSeason": "2002",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "24",
        "scoreAway": "22",
        "teamAway": "San Diego Chargers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "KC",
        "spreadFavorite": "-1.5",
        "overUnder": "44",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "11",
        "weatherHumidity": "63",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2002-12-29",
        "scheduleSeason": "2002",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Chicago Bears",
        "scoreHome": "0",
        "scoreAway": "15",
        "teamAway": "Tampa Bay Buccaneers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "TB",
        "spreadFavorite": "-7",
        "overUnder": "32",
        "stadium": "Memorial Stadium (Champaign)",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "10",
        "weatherHumidity": "85",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-11-09",
        "scheduleSeason": "2003",
        "scheduleWeek": "10",
        "schedulePlayoff": "FALSE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "28",
        "scoreAway": "15",
        "teamAway": "Arizona Cardinals",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PIT",
        "spreadFavorite": "-7",
        "overUnder": "40.5",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "31",
        "weatherWindMph": "7",
        "weatherHumidity": "49",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-12-07",
        "scheduleSeason": "2003",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "New England Patriots",
        "scoreHome": "12",
        "scoreAway": "0",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "NE",
        "spreadFavorite": "-3",
        "overUnder": "33.5",
        "stadium": "Gillette Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "27",
        "weatherWindMph": "24",
        "weatherHumidity": "85",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-12-07",
        "scheduleSeason": "2003",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Philadelphia Eagles",
        "scoreHome": "36",
        "scoreAway": "10",
        "teamAway": "Dallas Cowboys",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PHI",
        "spreadFavorite": "-5.5",
        "overUnder": "35.5",
        "stadium": "Lincoln Financial Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "20",
        "weatherHumidity": "63",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-12-07",
        "scheduleSeason": "2003",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "27",
        "scoreAway": "7",
        "teamAway": "Oakland Raiders",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PIT",
        "spreadFavorite": "-5.5",
        "overUnder": "40.5",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "11",
        "weatherHumidity": "88",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-12-08",
        "scheduleSeason": "2003",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cleveland Browns",
        "scoreHome": "20",
        "scoreAway": "26",
        "teamAway": "St. Louis Rams",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "LAR",
        "spreadFavorite": "-5.5",
        "overUnder": "43.5",
        "stadium": "FirstEnergy Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "27",
        "weatherWindMph": "8",
        "weatherHumidity": "76",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-12-14",
        "scheduleSeason": "2003",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cincinnati Bengals",
        "scoreHome": "41",
        "scoreAway": "38",
        "teamAway": "San Francisco 49ers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CIN",
        "spreadFavorite": "-3",
        "overUnder": "42",
        "stadium": "Paul Brown Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "29",
        "weatherWindMph": "10",
        "weatherHumidity": "92",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-12-14",
        "scheduleSeason": "2003",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "New England Patriots",
        "scoreHome": "27",
        "scoreAway": "13",
        "teamAway": "Jacksonville Jaguars",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "NE",
        "spreadFavorite": "-6",
        "overUnder": "33",
        "stadium": "Gillette Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "23",
        "weatherWindMph": "14",
        "weatherHumidity": "50",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-12-21",
        "scheduleSeason": "2003",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "3",
        "scoreAway": "20",
        "teamAway": "Miami Dolphins",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "BUF",
        "spreadFavorite": "-3",
        "overUnder": "33",
        "stadium": "Ralph Wilson Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "31",
        "weatherWindMph": "20",
        "weatherHumidity": "63",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-12-21",
        "scheduleSeason": "2003",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Philadelphia Eagles",
        "scoreHome": "28",
        "scoreAway": "31",
        "teamAway": "San Francisco 49ers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "PHI",
        "spreadFavorite": "-7",
        "overUnder": "44",
        "stadium": "Lincoln Financial Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "14",
        "weatherHumidity": "52",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2003-12-21",
        "scheduleSeason": "2003",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "40",
        "scoreAway": "24",
        "teamAway": "San Diego Chargers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PIT",
        "spreadFavorite": "-6.5",
        "overUnder": "42",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "10",
        "weatherHumidity": "73",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2004-11-28",
        "scheduleSeason": "2004",
        "scheduleWeek": "12",
        "schedulePlayoff": "FALSE",
        "teamHome": "Denver Broncos",
        "scoreHome": "24",
        "scoreAway": "25",
        "teamAway": "Oakland Raiders",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "DEN",
        "spreadFavorite": "-11.5",
        "overUnder": "42.5",
        "stadium": "Sports Authority Field at Mile High",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "15",
        "weatherHumidity": "88",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2004-11-29",
        "scheduleSeason": "2004",
        "scheduleWeek": "12",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "45",
        "scoreAway": "17",
        "teamAway": "St. Louis Rams",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-7",
        "overUnder": "51",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "31",
        "weatherWindMph": "6",
        "weatherHumidity": "80",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2004-12-19",
        "scheduleSeason": "2004",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Chicago Bears",
        "scoreHome": "5",
        "scoreAway": "24",
        "teamAway": "Houston Texans",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "CHI",
        "spreadFavorite": "-1",
        "overUnder": "34",
        "stadium": "Soldier Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "14",
        "weatherWindMph": "20",
        "weatherHumidity": "56",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2004-12-19",
        "scheduleSeason": "2004",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cleveland Browns",
        "scoreHome": "0",
        "scoreAway": "21",
        "teamAway": "San Diego Chargers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "LAC",
        "spreadFavorite": "-8",
        "overUnder": "35",
        "stadium": "FirstEnergy Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "18",
        "weatherHumidity": "81",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2004-12-19",
        "scheduleSeason": "2004",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "25",
        "scoreAway": "28",
        "teamAway": "Jacksonville Jaguars",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "GB",
        "spreadFavorite": "-3.5",
        "overUnder": "37",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "7",
        "weatherWindMph": "19",
        "weatherHumidity": "48",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2004-12-25",
        "scheduleSeason": "2004",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "31",
        "scoreAway": "30",
        "teamAway": "Oakland Raiders",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "KC",
        "spreadFavorite": "-9.5",
        "overUnder": "60",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "27",
        "weatherWindMph": "17",
        "weatherHumidity": "55",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2005-12-04",
        "scheduleSeason": "2005",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cleveland Browns",
        "scoreHome": "14",
        "scoreAway": "20",
        "teamAway": "Jacksonville Jaguars",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "JAX",
        "spreadFavorite": "-3",
        "overUnder": "36.5",
        "stadium": "FirstEnergy Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "27",
        "weatherWindMph": "10",
        "weatherHumidity": "78",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2005-12-18",
        "scheduleSeason": "2005",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Chicago Bears",
        "scoreHome": "16",
        "scoreAway": "3",
        "teamAway": "Atlanta Falcons",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CHI",
        "spreadFavorite": "-3",
        "overUnder": "30.5",
        "stadium": "Soldier Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "12",
        "weatherWindMph": "10",
        "weatherHumidity": "68",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2006-01-01",
        "scheduleSeason": "2005",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "New England Patriots",
        "scoreHome": "26",
        "scoreAway": "28",
        "teamAway": "Miami Dolphins",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "NE",
        "spreadFavorite": "-3",
        "overUnder": "37",
        "stadium": "Gillette Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "11",
        "weatherHumidity": "83",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2006-12-03",
        "scheduleSeason": "2006",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "21",
        "scoreAway": "24",
        "teamAway": "San Diego Chargers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "LAC",
        "spreadFavorite": "-5.5",
        "overUnder": "42.5",
        "stadium": "Ralph Wilson Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "13",
        "weatherHumidity": "73",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2006-12-03",
        "scheduleSeason": "2006",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "20",
        "scoreAway": "3",
        "teamAway": "Tampa Bay Buccaneers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PIT",
        "spreadFavorite": "-7",
        "overUnder": "41",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "6",
        "weatherHumidity": "63",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2006-12-31",
        "scheduleSeason": "2006",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Denver Broncos",
        "scoreHome": "23",
        "scoreAway": "26",
        "teamAway": "San Francisco 49ers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "DEN",
        "spreadFavorite": "-10",
        "overUnder": "39",
        "stadium": "Sports Authority Field at Mile High",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "21",
        "weatherWindMph": "7",
        "weatherHumidity": "54",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2007-11-25",
        "scheduleSeason": "2007",
        "scheduleWeek": "12",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cleveland Browns",
        "scoreHome": "27",
        "scoreAway": "17",
        "teamAway": "Houston Texans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CLE",
        "spreadFavorite": "-3",
        "overUnder": "52",
        "stadium": "FirstEnergy Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "8",
        "weatherHumidity": "64",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2007-11-25",
        "scheduleSeason": "2007",
        "scheduleWeek": "12",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "17",
        "scoreAway": "20",
        "teamAway": "Oakland Raiders",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "KC",
        "spreadFavorite": "-4",
        "overUnder": "34.5",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "8",
        "weatherHumidity": "79",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2007-12-09",
        "scheduleSeason": "2007",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "38",
        "scoreAway": "17",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "BUF",
        "spreadFavorite": "-7",
        "overUnder": "34",
        "stadium": "Ralph Wilson Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "7",
        "weatherHumidity": "73",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2007-12-09",
        "scheduleSeason": "2007",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "38",
        "scoreAway": "7",
        "teamAway": "Oakland Raiders",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-10",
        "overUnder": "40.5",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "17",
        "weatherWindMph": "5",
        "weatherHumidity": "62",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2007-12-16",
        "scheduleSeason": "2007",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "17",
        "scoreAway": "26",
        "teamAway": "Tennessee Titans",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "TEN",
        "spreadFavorite": "-3.5",
        "overUnder": "34.5",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "17",
        "weatherWindMph": "9",
        "weatherHumidity": "80",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2007-12-30",
        "scheduleSeason": "2007",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Chicago Bears",
        "scoreHome": "33",
        "scoreAway": "25",
        "teamAway": "New Orleans Saints",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CHI",
        "spreadFavorite": "-1",
        "overUnder": "42",
        "stadium": "Soldier Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "26",
        "weatherWindMph": "9",
        "weatherHumidity": "81",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2007-12-30",
        "scheduleSeason": "2007",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cleveland Browns",
        "scoreHome": "20",
        "scoreAway": "7",
        "teamAway": "San Francisco 49ers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CLE",
        "spreadFavorite": "-11.5",
        "overUnder": "41",
        "stadium": "FirstEnergy Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "6",
        "weatherHumidity": "67",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-11-23",
        "scheduleSeason": "2008",
        "scheduleWeek": "12",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cleveland Browns",
        "scoreHome": "6",
        "scoreAway": "16",
        "teamAway": "Houston Texans",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "CLE",
        "spreadFavorite": "-3",
        "overUnder": "49.5",
        "stadium": "FirstEnergy Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "7",
        "weatherHumidity": "66",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-11-30",
        "scheduleSeason": "2008",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "3",
        "scoreAway": "10",
        "teamAway": "San Francisco 49ers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "BUF",
        "spreadFavorite": "-6.5",
        "overUnder": "43",
        "stadium": "Ralph Wilson Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "31",
        "weatherWindMph": "11",
        "weatherHumidity": "75",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-11-30",
        "scheduleSeason": "2008",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "31",
        "scoreAway": "35",
        "teamAway": "Carolina Panthers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "GB",
        "spreadFavorite": "-3",
        "overUnder": "41.5",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "9",
        "weatherHumidity": "83",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-12-07",
        "scheduleSeason": "2008",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Chicago Bears",
        "scoreHome": "23",
        "scoreAway": "10",
        "teamAway": "Jacksonville Jaguars",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CHI",
        "spreadFavorite": "-6.5",
        "overUnder": "40",
        "stadium": "Soldier Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "13",
        "weatherWindMph": "13",
        "weatherHumidity": "63",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-12-07",
        "scheduleSeason": "2008",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "21",
        "scoreAway": "24",
        "teamAway": "Houston Texans",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "GB",
        "spreadFavorite": "-7",
        "overUnder": "47.5",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "6",
        "weatherWindMph": "10",
        "weatherHumidity": "71",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-12-07",
        "scheduleSeason": "2008",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "20",
        "scoreAway": "13",
        "teamAway": "Dallas Cowboys",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PIT",
        "spreadFavorite": "-4",
        "overUnder": "38.5",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "20",
        "weatherHumidity": "66",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-12-11",
        "scheduleSeason": "2008",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Chicago Bears",
        "scoreHome": "27",
        "scoreAway": "24",
        "teamAway": "New Orleans Saints",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CHI",
        "spreadFavorite": "-3",
        "overUnder": "46",
        "stadium": "Soldier Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "8",
        "weatherHumidity": "69",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-12-21",
        "scheduleSeason": "2008",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "31",
        "scoreAway": "38",
        "teamAway": "Miami Dolphins",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "MIA",
        "spreadFavorite": "-3.5",
        "overUnder": "37.5",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "4",
        "weatherWindMph": "16",
        "weatherHumidity": "56",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-12-21",
        "scheduleSeason": "2008",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "New England Patriots",
        "scoreHome": "47",
        "scoreAway": "7",
        "teamAway": "Arizona Cardinals",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "NE",
        "spreadFavorite": "-8",
        "overUnder": "41",
        "stadium": "Gillette Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "27",
        "weatherWindMph": "24",
        "weatherHumidity": "86",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2008-12-21",
        "scheduleSeason": "2008",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "New York Giants",
        "scoreHome": "34",
        "scoreAway": "28",
        "teamAway": "Carolina Panthers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "NYG",
        "spreadFavorite": "-4",
        "overUnder": "38",
        "stadium": "Giants Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "31",
        "weatherWindMph": "18",
        "weatherHumidity": "82",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2009-12-06",
        "scheduleSeason": "2009",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "24",
        "scoreAway": "27",
        "teamAway": "Oakland Raiders",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "PIT",
        "spreadFavorite": "-15",
        "overUnder": "37",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "26",
        "weatherWindMph": "6",
        "weatherHumidity": "70",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2009-12-20",
        "scheduleSeason": "2009",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "New York Jets",
        "scoreHome": "7",
        "scoreAway": "10",
        "teamAway": "Atlanta Falcons",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "NYJ",
        "spreadFavorite": "-7",
        "overUnder": "35.5",
        "stadium": "Giants Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "29",
        "weatherWindMph": "21",
        "weatherHumidity": "62",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2010-01-03",
        "scheduleSeason": "2009",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Carolina Panthers",
        "scoreHome": "23",
        "scoreAway": "10",
        "teamAway": "New Orleans Saints",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CAR",
        "spreadFavorite": "-10",
        "overUnder": "41",
        "stadium": "Bank of America Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "31",
        "weatherWindMph": "8",
        "weatherHumidity": "42",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2010-01-03",
        "scheduleSeason": "2009",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cleveland Browns",
        "scoreHome": "23",
        "scoreAway": "17",
        "teamAway": "Jacksonville Jaguars",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CLE",
        "spreadFavorite": "-2",
        "overUnder": "35",
        "stadium": "FirstEnergy Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "18",
        "weatherWindMph": "17",
        "weatherHumidity": "67",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2010-12-05",
        "scheduleSeason": "2010",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cincinnati Bengals",
        "scoreHome": "30",
        "scoreAway": "34",
        "teamAway": "New Orleans Saints",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "NO",
        "spreadFavorite": "-7",
        "overUnder": "45.5",
        "stadium": "Paul Brown Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "1",
        "weatherHumidity": "68",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2010-12-05",
        "scheduleSeason": "2010",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "34",
        "scoreAway": "16",
        "teamAway": "San Francisco 49ers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-9",
        "overUnder": "41",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "26",
        "weatherWindMph": "1",
        "weatherHumidity": "60",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2010-12-23",
        "scheduleSeason": "2010",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "27",
        "scoreAway": "3",
        "teamAway": "Carolina Panthers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PIT",
        "spreadFavorite": "-14.5",
        "overUnder": "38",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "27",
        "weatherWindMph": "1",
        "weatherHumidity": "70",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2010-12-26",
        "scheduleSeason": "2010",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cincinnati Bengals",
        "scoreHome": "34",
        "scoreAway": "20",
        "teamAway": "San Diego Chargers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "LAC",
        "spreadFavorite": "-8",
        "overUnder": "43.5",
        "stadium": "Paul Brown Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "1",
        "weatherHumidity": "62",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2010-12-26",
        "scheduleSeason": "2010",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "34",
        "scoreAway": "14",
        "teamAway": "Tennessee Titans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "KC",
        "spreadFavorite": "-4",
        "overUnder": "42.5",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "19",
        "weatherWindMph": "7",
        "weatherHumidity": "77",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2011-01-02",
        "scheduleSeason": "2010",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "10",
        "scoreAway": "31",
        "teamAway": "Oakland Raiders",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "KC",
        "spreadFavorite": "-4.5",
        "overUnder": "43.5",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "1",
        "weatherHumidity": "40",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2011-11-20",
        "scheduleSeason": "2011",
        "scheduleWeek": "11",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "35",
        "scoreAway": "26",
        "teamAway": "Tampa Bay Buccaneers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-13.5",
        "overUnder": "49",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "7",
        "weatherHumidity": "66",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2011-12-18",
        "scheduleSeason": "2011",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "23",
        "scoreAway": "30",
        "teamAway": "Miami Dolphins",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "BUF",
        "spreadFavorite": "-1.5",
        "overUnder": "40.5",
        "stadium": "Ralph Wilson Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "1",
        "weatherHumidity": "64",
        "weatherDetail": "snow"
    },
    {
        "scheduleDate": "2011-12-24",
        "scheduleSeason": "2011",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "New England Patriots",
        "scoreHome": "27",
        "scoreAway": "24",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "NE",
        "spreadFavorite": "-7.5",
        "overUnder": "49.5",
        "stadium": "Gillette Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "7",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2012-12-23",
        "scheduleSeason": "2012",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "55",
        "scoreAway": "7",
        "teamAway": "Tennessee Titans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-11",
        "overUnder": "44.5",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "9",
        "weatherHumidity": "68",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2012-12-30",
        "scheduleSeason": "2012",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "New England Patriots",
        "scoreHome": "28",
        "scoreAway": "0",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "NE",
        "spreadFavorite": "-10",
        "overUnder": "46.5",
        "stadium": "Gillette Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "13",
        "weatherHumidity": "45",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2013-11-24",
        "scheduleSeason": "2013",
        "scheduleWeek": "12",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "38",
        "scoreAway": "41",
        "teamAway": "San Diego Chargers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "KC",
        "spreadFavorite": "-3",
        "overUnder": "42.5",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "4",
        "weatherHumidity": "50",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2013-11-24",
        "scheduleSeason": "2013",
        "scheduleWeek": "12",
        "schedulePlayoff": "FALSE",
        "teamHome": "New York Giants",
        "scoreHome": "21",
        "scoreAway": "24",
        "teamAway": "Dallas Cowboys",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "NYG",
        "spreadFavorite": "-2.5",
        "overUnder": "44",
        "stadium": "MetLife Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "26",
        "weatherWindMph": "7",
        "weatherHumidity": "40",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2013-12-08",
        "scheduleSeason": "2013",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Denver Broncos",
        "scoreHome": "51",
        "scoreAway": "28",
        "teamAway": "Tennessee Titans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "DEN",
        "spreadFavorite": "-13.5",
        "overUnder": "49.5",
        "stadium": "Sports Authority Field at Mile High",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "19",
        "weatherWindMph": "7",
        "weatherHumidity": "63",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2013-12-08",
        "scheduleSeason": "2013",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "22",
        "scoreAway": "21",
        "teamAway": "Atlanta Falcons",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-3.5",
        "overUnder": "45",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "9",
        "weatherWindMph": "9",
        "weatherHumidity": "80",
        "weatherDetail": "snow"
    },
    {
        "scheduleDate": "2013-12-08",
        "scheduleSeason": "2013",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "28",
        "scoreAway": "34",
        "teamAway": "Miami Dolphins",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "PIT",
        "spreadFavorite": "-3",
        "overUnder": "41",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "26",
        "weatherWindMph": "9",
        "weatherHumidity": "73",
        "weatherDetail": "snow | fog"
    },
    {
        "scheduleDate": "2013-12-09",
        "scheduleSeason": "2013",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Chicago Bears",
        "scoreHome": "45",
        "scoreAway": "28",
        "teamAway": "Dallas Cowboys",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CHI",
        "spreadFavorite": "-1.5",
        "overUnder": "49.5",
        "stadium": "Soldier Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "8",
        "weatherWindMph": "9",
        "weatherHumidity": "63",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2014-11-30",
        "scheduleSeason": "2014",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Minnesota Vikings",
        "scoreHome": "31",
        "scoreAway": "13",
        "teamAway": "Carolina Panthers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "MIN",
        "spreadFavorite": "-2.5",
        "overUnder": "41.5",
        "stadium": "TCF Bank Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "15",
        "weatherWindMph": "15",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2014-12-08",
        "scheduleSeason": "2014",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "43",
        "scoreAway": "37",
        "teamAway": "Atlanta Falcons",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-13.5",
        "overUnder": "55",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "4",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2015-01-11",
        "scheduleSeason": "2014",
        "scheduleWeek": "Division",
        "schedulePlayoff": "TRUE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "26",
        "scoreAway": "21",
        "teamAway": "Dallas Cowboys",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-5.5",
        "overUnder": "51.5",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "0",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2016-01-03",
        "scheduleSeason": "2015",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "23",
        "scoreAway": "17",
        "teamAway": "Oakland Raiders",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "KC",
        "spreadFavorite": "-6.5",
        "overUnder": "43.5",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "7",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2016-12-04",
        "scheduleSeason": "2016",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "21",
        "scoreAway": "13",
        "teamAway": "Houston Texans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-7",
        "overUnder": "44.5",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "31",
        "weatherWindMph": "4",
        "weatherHumidity": null,
        "weatherDetail": "snow"
    },
    {
        "scheduleDate": "2016-12-08",
        "scheduleSeason": "2016",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "21",
        "scoreAway": "13",
        "teamAway": "Oakland Raiders",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "KC",
        "spreadFavorite": "-3.5",
        "overUnder": "46",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "23",
        "weatherWindMph": "4",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2016-12-11",
        "scheduleSeason": "2016",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "New York Giants",
        "scoreHome": "10",
        "scoreAway": "7",
        "teamAway": "Dallas Cowboys",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "DAL",
        "spreadFavorite": "-3.5",
        "overUnder": "47",
        "stadium": "MetLife Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "2",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2016-12-18",
        "scheduleSeason": "2016",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Dallas Cowboys",
        "scoreHome": "26",
        "scoreAway": "20",
        "teamAway": "Tampa Bay Buccaneers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "DAL",
        "spreadFavorite": "-7",
        "overUnder": "47.5",
        "stadium": "Cowboys Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "26",
        "weatherWindMph": "7",
        "weatherHumidity": null,
        "weatherDetail": "retractable (open roof)"
    },
    {
        "scheduleDate": "2016-12-18",
        "scheduleSeason": "2016",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "17",
        "scoreAway": "19",
        "teamAway": "Tennessee Titans",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "KC",
        "spreadFavorite": "-6",
        "overUnder": "43",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "2",
        "weatherWindMph": "2",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2016-12-19",
        "scheduleSeason": "2016",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Washington Redskins",
        "scoreHome": "15",
        "scoreAway": "26",
        "teamAway": "Carolina Panthers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "WAS",
        "spreadFavorite": "-7",
        "overUnder": "50.5",
        "stadium": "FedEx Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "3",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2017-01-08",
        "scheduleSeason": "2016",
        "scheduleWeek": "Wildcard",
        "schedulePlayoff": "TRUE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "30",
        "scoreAway": "12",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PIT",
        "spreadFavorite": "-11",
        "overUnder": "47.5",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "17",
        "weatherWindMph": "16",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2017-01-14",
        "scheduleSeason": "2016",
        "scheduleWeek": "Division",
        "schedulePlayoff": "TRUE",
        "teamHome": "New England Patriots",
        "scoreHome": "34",
        "scoreAway": "16",
        "teamAway": "Houston Texans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "NE",
        "spreadFavorite": "-16",
        "overUnder": "44",
        "stadium": "Gillette Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "6",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2017-12-17",
        "scheduleSeason": "2017",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "24",
        "scoreAway": "16",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "BUF",
        "spreadFavorite": "-3.5",
        "overUnder": "39.5",
        "stadium": "New Era Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "22",
        "weatherWindMph": "8",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2017-12-24",
        "scheduleSeason": "2017",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "29",
        "scoreAway": "13",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "KC",
        "spreadFavorite": "-11",
        "overUnder": "43.5",
        "stadium": "Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "23",
        "weatherWindMph": "15",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2017-12-25",
        "scheduleSeason": "2017",
        "scheduleWeek": "16",
        "schedulePlayoff": "FALSE",
        "teamHome": "Philadelphia Eagles",
        "scoreHome": "19",
        "scoreAway": "10",
        "teamAway": "Oakland Raiders",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PHI",
        "spreadFavorite": "-10",
        "overUnder": "46",
        "stadium": "Lincoln Financial Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "29",
        "weatherWindMph": "15",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2017-12-31",
        "scheduleSeason": "2017",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Philadelphia Eagles",
        "scoreHome": "0",
        "scoreAway": "6",
        "teamAway": "Dallas Cowboys",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "DAL",
        "spreadFavorite": "-3.5",
        "overUnder": "41",
        "stadium": "Lincoln Financial Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "19",
        "weatherWindMph": "17",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2017-12-31",
        "scheduleSeason": "2017",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Tennessee Titans",
        "scoreHome": "15",
        "scoreAway": "10",
        "teamAway": "Jacksonville Jaguars",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "TEN",
        "spreadFavorite": "-2.5",
        "overUnder": "40",
        "stadium": "LP Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "23",
        "weatherWindMph": "5",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2018-01-13",
        "scheduleSeason": "2017",
        "scheduleWeek": "Division",
        "schedulePlayoff": "TRUE",
        "teamHome": "New England Patriots",
        "scoreHome": "35",
        "scoreAway": "14",
        "teamAway": "Tennessee Titans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "NE",
        "spreadFavorite": "-13.5",
        "overUnder": "48.5",
        "stadium": "Gillette Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "24",
        "weatherWindMph": "12",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2018-01-13",
        "scheduleSeason": "2017",
        "scheduleWeek": "Division",
        "schedulePlayoff": "TRUE",
        "teamHome": "Philadelphia Eagles",
        "scoreHome": "15",
        "scoreAway": "10",
        "teamAway": "Atlanta Falcons",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "ATL",
        "spreadFavorite": "-2.5",
        "overUnder": "40",
        "stadium": "Lincoln Financial Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "16",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2018-01-14",
        "scheduleSeason": "2017",
        "scheduleWeek": "Division",
        "schedulePlayoff": "TRUE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "42",
        "scoreAway": "45",
        "teamAway": "Jacksonville Jaguars",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "PIT",
        "spreadFavorite": "-7",
        "overUnder": "40.5",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "18",
        "weatherWindMph": "2",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2018-10-14",
        "scheduleSeason": "2018",
        "scheduleWeek": "6",
        "schedulePlayoff": "FALSE",
        "teamHome": "Denver Broncos",
        "scoreHome": "20",
        "scoreAway": "23",
        "teamAway": "Los Angeles Rams",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "LAR",
        "spreadFavorite": "-7",
        "overUnder": "50",
        "stadium": "Sports Authority Field at Mile High",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "25",
        "weatherWindMph": "6",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2018-12-09",
        "scheduleSeason": "2018",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Chicago Bears",
        "scoreHome": "15",
        "scoreAway": "6",
        "teamAway": "Los Angeles Rams",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "LAR",
        "spreadFavorite": "-3",
        "overUnder": "51",
        "stadium": "Soldier Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "29",
        "weatherWindMph": "4",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2018-12-09",
        "scheduleSeason": "2018",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Cleveland Browns",
        "scoreHome": "26",
        "scoreAway": "20",
        "teamAway": "Carolina Panthers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CAR",
        "spreadFavorite": "-1",
        "overUnder": "47.5",
        "stadium": "FirstEnergy Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "4",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2018-12-09",
        "scheduleSeason": "2018",
        "scheduleWeek": "14",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "34",
        "scoreAway": "20",
        "teamAway": "Atlanta Falcons",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-4",
        "overUnder": "50.5",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "25",
        "weatherWindMph": "10",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2019-01-13",
        "scheduleSeason": "2018",
        "scheduleWeek": "Division",
        "schedulePlayoff": "TRUE",
        "teamHome": "New England Patriots",
        "scoreHome": "41",
        "scoreAway": "28",
        "teamAway": "Los Angeles Chargers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "NE",
        "spreadFavorite": "-3.5",
        "overUnder": "47.5",
        "stadium": "Gillette Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "26",
        "weatherWindMph": "3",
        "weatherHumidity": null,
        "weatherDetail": null
    },
    {
        "scheduleDate": "2021-01-24",
        "scheduleSeason": "2020",
        "scheduleWeek": "Conference",
        "schedulePlayoff": "TRUE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "26",
        "scoreAway": "31",
        "teamAway": "Tampa Bay Buccaneers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "GB",
        "spreadFavorite": "-3",
        "overUnder": "53",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "29",
        "weatherWindMph": "10",
        "weatherHumidity": "75",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2021-12-19",
        "scheduleSeason": "2021",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "31",
        "scoreAway": "14",
        "teamAway": "Carolina Panthers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "BUF",
        "spreadFavorite": "-14.5",
        "overUnder": "43",
        "stadium": "Highmark Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "30",
        "weatherWindMph": "8",
        "weatherHumidity": "69",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2021-12-19",
        "scheduleSeason": "2021",
        "scheduleWeek": "15",
        "schedulePlayoff": "FALSE",
        "teamHome": "Pittsburgh Steelers",
        "scoreHome": "19",
        "scoreAway": "13",
        "teamAway": "Tennessee Titans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "PIT",
        "spreadFavorite": "-1",
        "overUnder": "44",
        "stadium": "Heinz Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "32",
        "weatherWindMph": "11",
        "weatherHumidity": "74",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2022-01-02",
        "scheduleSeason": "2021",
        "scheduleWeek": "17",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "29",
        "scoreAway": "15",
        "teamAway": "Atlanta Falcons",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "BUF",
        "spreadFavorite": "-14",
        "overUnder": "46",
        "stadium": "Highmark Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "26",
        "weatherWindMph": "11",
        "weatherHumidity": "81",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2022-01-08",
        "scheduleSeason": "2021",
        "scheduleWeek": "18",
        "schedulePlayoff": "FALSE",
        "teamHome": "Philadelphia Eagles",
        "scoreHome": "26",
        "scoreAway": "51",
        "teamAway": "Dallas Cowboys",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "DAL",
        "spreadFavorite": "-6",
        "overUnder": "46.5",
        "stadium": "Lincoln Financial Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "31",
        "weatherWindMph": "8",
        "weatherHumidity": "43",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2022-01-15",
        "scheduleSeason": "2021",
        "scheduleWeek": "Wildcard",
        "schedulePlayoff": "TRUE",
        "teamHome": "Cincinnati Bengals",
        "scoreHome": "26",
        "scoreAway": "19",
        "teamAway": "Las Vegas Raiders",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "CIN",
        "spreadFavorite": "-6",
        "overUnder": "48.5",
        "stadium": "Paul Brown Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "31",
        "weatherWindMph": "12",
        "weatherHumidity": "63",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2022-01-22",
        "scheduleSeason": "2021",
        "scheduleWeek": "Division",
        "schedulePlayoff": "TRUE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "10",
        "scoreAway": "13",
        "teamAway": "San Francisco 49ers",
        "homeResult": "LOSS",
        "awayResult": "WIN",
        "teamFavId": "GB",
        "spreadFavorite": "-5.5",
        "overUnder": "47",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "15",
        "weatherWindMph": "12",
        "weatherHumidity": "53",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2023-01-15",
        "scheduleSeason": "2022",
        "scheduleWeek": "Wildcard",
        "schedulePlayoff": "TRUE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "34",
        "scoreAway": "31",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "BUF",
        "spreadFavorite": "-14",
        "overUnder": "44.5",
        "stadium": "Highmark Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "27",
        "weatherWindMph": "4",
        "weatherHumidity": "80",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2024-01-13",
        "scheduleSeason": "2023",
        "scheduleWeek": "Wildcard",
        "schedulePlayoff": "TRUE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "26",
        "scoreAway": "7",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "KC",
        "spreadFavorite": "-4.5",
        "overUnder": "43.5",
        "stadium": "GEHA Field at Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "-4",
        "weatherWindMph": "19",
        "weatherHumidity": "64",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2024-01-20",
        "scheduleSeason": "2023",
        "scheduleWeek": "Division",
        "schedulePlayoff": "TRUE",
        "teamHome": "Baltimore Ravens",
        "scoreHome": "34",
        "scoreAway": "10",
        "teamAway": "Houston Texans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "BAL",
        "spreadFavorite": "-10",
        "overUnder": "44",
        "stadium": "M&T Bank Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "27",
        "weatherWindMph": "16",
        "weatherHumidity": "40",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2024-11-28",
        "scheduleSeason": "2024",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Green Bay Packers",
        "scoreHome": "30",
        "scoreAway": "17",
        "teamAway": "Miami Dolphins",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "GB",
        "spreadFavorite": "-3.5",
        "overUnder": "47.5",
        "stadium": "Lambeau Field",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "27",
        "weatherWindMph": "10",
        "weatherHumidity": "63",
        "weatherDetail": null
    },
    {
        "scheduleDate": "2024-12-01",
        "scheduleSeason": "2024",
        "scheduleWeek": "13",
        "schedulePlayoff": "FALSE",
        "teamHome": "Buffalo Bills",
        "scoreHome": "35",
        "scoreAway": "10",
        "teamAway": "San Francisco 49ers",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "BUF",
        "spreadFavorite": "-6.5",
        "overUnder": "45.5",
        "stadium": "Highmark Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "28",
        "weatherWindMph": "11",
        "weatherHumidity": "79",
        "weatherDetail": "snow"
    },
    {
        "scheduleDate": "2025-01-18",
        "scheduleSeason": "2024",
        "scheduleWeek": "Division",
        "schedulePlayoff": "TRUE",
        "teamHome": "Kansas City Chiefs",
        "scoreHome": "23",
        "scoreAway": "14",
        "teamAway": "Houston Texans",
        "homeResult": "WIN",
        "awayResult": "LOSS",
        "teamFavId": "KC",
        "spreadFavorite": "-9.5",
        "overUnder": "41.5",
        "stadium": "GEHA Field at Arrowhead Stadium",
        "stadiumNeutral": "FALSE",
        "weatherTemp": "23",
        "weatherWindMph": "17",
        "weatherHumidity": "43",
        "weatherDetail": null
    }
]